# Application Name
spring.application.name=random-idea-generator

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://dpg-d6qitjn5gffc73eqm0r0-a.oregon-postgres.render.com:5432/idea_generator_db
spring.datasource.username=idea_generator_db_user
spring.datasource.password=8EOnm0Dg6M3SbevXQpGnWRkSfL0na077
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server Port
server.port=8080